### ISSUE TITLE
エレベーター呼び出しpayloadのvalidation処理がほしい

### ISSUE THREAD

**Issue by KenyuKurimoto** [octarobotics/lci-rmf-adapter#7]
## 概要

`CallElevator` API利用時に、payload中の`origination`と`destination`の値が同じ場合は不適切な値としてエレベーター側で処理されてしまう。

これを避けるため、下記の箇所などで、publishする前に与えられた`origination`と`destination`が一致しているときは送信せずに無視するような処理を加えるべきである。

https://github.com/octarobotics/lci-rmf-adapter/blob/844edae984ed39d2ebf6650f045af09b193b0304/lci_rmf_adapter/lci_rmf_adapter/lci_client.py#L515-L541

**Comment by nabeshima** [comment]
プルリク有難うございます。

RMFからくるLiftRequestのバリデーションは、最初に受け付けた

[ lci_rmf_adapter/lci_rmf_adapter/lci_rmf_adapter.py 
](https://github.com/octarobotics/lci-rmf-adapter/blob/844edae984ed39d2ebf6650f045af09b193b0304/lci_rmf_adapter/lci_rmf_adapter/lci_rmf_adapter.py)

でやっておりますので、そちらを修正することにいたしました。

以下のコミットにてサポートしましたので、mainをpullしてご利用下さい。
https://github.com/octarobotics/lci-rmf-adapter/commit/abaf30dd10810ec6dfb2bd0a2d67c8d83c770b7c

ご指摘頂き有難うございました。

**Comment by KenyuKurimoto** [comment]
ご対応ありがとうございました。

**Comment by h-wata** [comment]
間があいて恐縮です。

https://github.com/octarobotics/lci-rmf-adapter/blob/abaf30dd10810ec6dfb2bd0a2d67c8d83c770b7c/lci_rmf_adapter/lci_rmf_adapter/lci_rmf_adapter.py#L309-L322

こちらの`Example 3`のようにケージ内で乗り込み完了を伝える際に、`3F:3F`のように`destination_floor`を伝えると、下記のValidation checkに引っかかってしまうのですがこちら仕様でしょうか？
箱内から閉要求を出すときにErrorになってしまいます。

**Comment by KenyuKurimoto** [comment]
私も確認不足だったので申し訳ないのですが、私の遭遇したトラブルは特に**特定のエレベーターベンダーの機能をラッピングする形でLCIのAPIが用いられている場合**についてのものでして、この場合

- `LciRmfAdapter`クラスでは、originationとdestinationが同じメッセージを受けつけてもOK（RMF側ではこういったメッセージを許容できるようにしないと上述の例のように逆にうまくいかない）
- `LciClient`クラスでは、originationとdestinationを送るとサーバー側で問題が起こるためこれをvalidationして防ぐべき

という認識でおります。以前の #8 を使った場合は問題なく動いております。

**Comment by nabeshima** [comment]
ご指摘頂き有難うございます。
仰るとおり、

> 3F:3Fのようにdestination_floor

というパターンですと、意図せずvalidationで弾かれておりました。


以下のコミットにて修正いたしましたので、ご確認頂けますでしょうか？
https://github.com/octarobotics/lci-rmf-adapter/commit/44edb414a6280dadc28bbb51aa6ccdcf7a46b04c
